services:
    backend:
        build:
            context: ./server
            dockerfile: Dockerfile
        container_name: server
        restart: always
        ports:
            - "5500:5500"
        env_file:
            - ./server/.env
        environment:
            DB_HOST: "postgres_db"
            DB_USER: "bible_user"
            DB_PASSWORD: "bible_password"
            DB_NAME: "bible_db"
            DB_DIALECT: "postgres"
            DB_PORT: "5432"
            GOOGLE_APPLICATION_CREDENTIALS: /app/keys/diesel-client-451019-e1-bddafd5b6b3f.json
        volumes:
            - ./server/keys:/app/keys
        depends_on:
            - postgres_db

    frontend:
        build:
            context: ./client
            dockerfile: Dockerfile
        container_name: client
        restart: always
        ports:
            - "3000:80" # Map Nginx port 80 to localhost:3000
        depends_on:
            - backend

    postgres_db:
        image: postgres:latest
        container_name: postgres_db
        restart: always
        environment:
            POSTGRES_DB: bible_db
            POSTGRES_USER: bible_user
            POSTGRES_PASSWORD: bible_password
        ports:
            - "5432:5432"
        volumes:
            - postgres_data:/var/lib/postgresql/data

volumes:
    postgres_data:
