version: "3.8"

services:
    mysql:
        image: mysql:latest
        container_name: mysql_db
        restart: always
        environment:
            MYSQL_ROOT_PASSWORD: root_password
            MYSQL_DATABASE: bible_db
            MYSQL_USER: bible_user
            MYSQL_PASSWORD: bible_password
        ports:
            - "3306:3306"
        volumes:
            - mysql_data:/var/lib/mysql

volumes:
    mysql_data:
