version: "3.8"

services:
    postgres:
        image: postgres:16
        container_name: postgres_db
        restart: always
        environment:
            POSTGRES_USER: bible_user
            POSTGRES_PASSWORD: bible_password
            POSTGRES_DB: bible_db
        ports:
            - "5432:5432"
        volumes:
            - postgres_data:/var/lib/postgresql/data

volumes:
    postgres_data:
